### ISSUE TITLE
Fail to eval

### ISSUE THREAD

**Issue by nabilapuspit** [mahmoodlab/TOAD#9]
Hi, I tried to running the evaluation command
```
CUDA_VISIBLE_DEVICES=0 python eval_mtl_concat.py --drop_out --k 1 --models_exp_code dummy_mtl_sex_s1 --save_exp_code dummy_mtl_sex_s1_eval --task dummy_mtl_concat  --results_dir results --data_root_dir DATA_ROOT_DIR
```

I changed the task bellow code 
`--task study_v2_mtl_sex`
into 
`--task dummy_mtl_concat`
 because the study_v2_mtl_sex task couldn't found. But then I ran into this error:

> Traceback (most recent call last):
  File "eval_mtl_concat.py", line 122, in <module>
    model, results_dict = eval(split_dataset, args, ckpt_paths[ckpt_idx])
  File "/media/chingwei/bf764154-3611-460c-9bfd-4efed447a219/chingwei/Nabila/TOAD-NGS/utils/eval_utils_mtl_concat.py", line 40, in eval
    results_dict = summary(model, loader, args)
  File "/media/chingwei/bf764154-3611-460c-9bfd-4efed447a219/chingwei/Nabila/TOAD-NGS/utils/eval_utils_mtl_concat.py", line 120, in summary
    cls_test_error /= len(loader)
ZeroDivisionError: float division by zero

Could you please provide any guidance on how to resolve this error?
OS : ubuntu 
torch : 1.10.1+cu111

**Comment by nabilapuspit** [comment]
I further compared this method with the CLAM method and just found that the data read for evaluation in this program uses the splits_0.csv obtained from the training split and this causes a division by zero error because the program cannot find a file with the title contained in the csv because it's not an eval split file. because in the CLAM procedure I saw that there is a step for evaluation/testing splits. can the author add additional procedures if this is necessary?

**Comment by nabilapuspit** [comment]
I just found out that the program read the wrong csv to eval, that's why it caused float division by zero. all you need to do is just add  `--split all` to the whole args for eval so it will be like:
`CUDA_VISIBLE_DEVICES=0 python eval_mtl_concat.py --drop_out --k 1 --models_exp_code dummy_mtl_sex_s1 --save_exp_code dummy_mtl_sex_s1_eval --split all --task dummy_mtl_concat  --results_dir results --data_root_dir DATA_ROOT_DIR`
